<table class="product_table" width="100%">
        <tr>
            <td width="20%" class="listfield">
                 <div class="left-bar">
          <ul class="side-menu">
        <li><a href="<?php echo $this-> url(array("controller"=> "stockup", "action"=> "index",)); ?>">Stock up </a></li>
        <li><a href="<?php echo $this-> url(array("controller"=> "order", "action" => "index",)); ?>"> Order </a></li>
        <li><a href="<?php echo $this-> url(array("controller"=> "order", "action" => "orderhistory",)); ?>"> Order History</a></li>
        <li><a href="<?php echo $this-> url(array("controller"=> "supplier", "action"=>"index",)); ?>">Suppliers</a></li>
        </ul>
                     </div>          </td>
             <td width="1" bgcolor="black"></td> 
             <td width="80%" class="editfield">
             </td>
        </tr>
</table>