<table class="product_table" width="100%">
        <tr>
            <td width="20%" class="listfield">
          <ul class="side-menu">
        <li>Stock up</li>
        <li>Order </li>
        <li><a href="<?php echo $this-> url(array("controller"=> "stockup", "action"=>"index",)); ?>">Suppliers</a></li>
        </ul>
          </td>
             <td width="1" bgcolor="black"></td> 
             <td width="80%" class="editfield">
             </td>
        </tr>
</table>