<div class="Add-button">
<a href="<?php echo $this->url(array('controller' =>'surfboard', 'action'=>'add')); ?>">Add</a>
</div>
<table class="product_list">
    <caption>
        Surfboards    
    </caption>
    <tr>
       <td> Type </td>
       <td> Name </td>
       <td> Item Code </td>
       <td> Price </td>
       <td> Size </td>
       <td colspan ="2"> Action </td>
    </tr>
    
    <?php foreach ( $this -> all as $product) : ?>
    <tr>
      <td> <?php echo $product-> type; ?> </td>
      <td> <?php echo $product-> product_name; ?></td>
      <td> <?php echo $product-> item_code; ?></td>
      <td> <?php echo $product-> price; ?> </td>
      <td> <?php echo $product-> size; ?> </td>
      <td> 
           <a href="<?php echo $this->url(array("controller"=>"view", "action"=>"index","category"=> $product->product_category_id, "id"=>$product->product_id)); ?>">View</a>
           &nbsp;
           <a href="<?php echo $this->url(array("controller"=>"surfboard","action"=>"edit","id"=>$product->product_id)); ?>">Update</a>
           &nbsp;
           <a href="<?php echo $this->url(array("controller"=>"surfboard","action"=>"delete","id"=>$product->product_id)); ?>">Delete</a>
      </td>       
    </tr>
    <?php endforeach; ?>
</table>