<?php
   $this -> title = "Delete";
   $this -> headTitle($this -> Title);
   
?>

<p> Delete <?php echo $this -> escape($this -> product['product_name'] ); ?> ( <?php echo $this -> escape( $this -> product['item_code']); ?> )? </p>

<form action="<?php echo $this-> url (array("controller"=>"umbrela","action"=>"delete")); ?>" method ="post" >
    <div>
        <input type ="hidden" name="id" value="<?php echo $this -> product['product_id']; ?>" />
        <input type ="submit" name ="del" value ="Yes" />
        <input type ="submit" name ="del" value="No" />
    </div>
</form>