<script type="text/javascript">
    $(document).ready(function(){
         $("#category-element").after("<div id ='products'></div>");
         $("#category").change(function(){
          var category_id = $("#category").val();   
         
         $.ajax({
             type: "POST",
             url: "<?php echo $this -> url(array("controller"=> "stockup", "action"=> "product",)); ?>",
             data: {id: category_id},
             success: function(result){
                 $("#products").html(result);
             }
         });
//        alert(category_id);
      });
    });
   
</script>

<table class="product_table" width="100%">
        <tr class ="main-row">
          <td width="20%" class="listfield">  
              <div class="left-bar"></div>
          </td>
             <td width="1" bgcolor="black"></td> 
             <td width="80%" class="editfield">
                 <div class="right-bar">
                   <div id="view-content">
    
                   <?php echo $this -> form; ?>
                       <?php echo $this -> category; ?>
                       <?php echo $this -> product; ?>
                       <?php echo $this -> date; ?>
                   </div>
                 </div>
             </td>
        </tr>
</table>