<?php 
 $this->headMeta()->appendHttpEquiv('Content-Type','text/html;charset=utf-8');
 $this->headTitle()->setSeparator(' - ');
 $this->headTitle('Blackhawk Internation Pty Ltd');
 
 echo $this->doctype(); 
 ?>

<html xmlns="http://www.blackhawkinternation.com.au" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css')
                                    ->appendStylesheet($this->baseUrl().'/css/ui-lightness/jquery-ui-1.7.3.custom.css'); ?>
        <?php  echo $this->jQuery()->enable(); ?>
    </head>
  
    <body>
        <div id="header">
            <div id="logo"></div>
            <div id="header-menu">
                <ul>
                    <li><a href="<?php echo $this->url(array('controller'=>'catalog','action'=>'index')); ?>">Catalog</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'stockup')); ?>">Stock Up</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'sales','action'=>'index')); ?>">Sales</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'stock','action'=>'index')); ?>">Stock</a></li>
                    <li><a href="<?php echo $this->url(array('controller'=>'report','action'=>'index')); ?>">Reports</a></li>
                </ul>
            
            </div>
        </div>
        <div id="content">
            <h1><?php echo $this->escape($this->title); ?></h1>
            
           
             <?php echo $this->layout()->content;  //echo the current action to display ?>            
        </div>
        <div id="footer">
            <p>Storage Management System <br />
            Blackhawk International Pty Dtd </p>
        </div>        
    </body>   
    
</html>

