<script type="text/javascript">
    $(document).ready(function(){
         $("#category-element").after("<div id ='products'></div>");
         $("#category").change(function(){
          var category_id = $("#category").val();   
         
         $.ajax({
             type: "POST",
             url: "<?php echo $this -> url(array("controller"=> "stockup", "action"=> "product",)); ?>",
             data: {id: category_id},
             success: function(result){
                 $("#products").html(result);
             }
         });
//        alert(category_id);
      });
    });
   
</script>


<table class="product_table" width="100%">
        <tr class ="main-row">
          <td class="listfield">  
               <div class="left-bar">
              <ul class="side-menu">
                  <li>
                  <a href="<?php echo $this->url(array("controller" =>"sales", "action"=> "history",)); ?>">History</a>
                  </li>
              </ul>
               </div>
          </td>
             <td width="1" bgcolor="black"></td> 
             <td class="editfield">
                    <div id="view-content">
                        <h1>Sales</h1>
                        <?php echo $this -> form ; ?>
                    </div>
             </td>
        </tr>
</table>