<table class="product_table" width="100%">
        <tr class ="main-row">
          <td class="listfield">  
              <ul class="side-menu">
                  <li>
                  <a href="<?php echo $this->url(array("controller" =>"sales", "action"=> "history",)); ?>">History</a>
                  </li>
              </ul>
          </td>
             <td width="1" bgcolor="black"></td> 
             <td class="editfield">
                    <div id="view-content">
                        <h1>Sales Update</h1>
                        <?php echo $this -> form ; ?>
                    </div>
             </td>
        </tr>
</table>