<table class="product_table" width="100%">
        <tr>
          <td width="20%" class="listfield">  
              <div class="left-bar">
              <ul class="side-menu">
                  <li><a href="<?php echo $this->url(array('controller'=>'catalog', 'action'=>'category')); ?>" >Category</a></li>
                  <li><a href="<?php echo $this->url(array('controller'=>'catalog', 'action'=>'editcategory')); ?>" >Product</a></li>
              </ul>
              </div>
          </td>
             
          <td width="1" bgcolor="black"></td> 
             
          <td width="80%" class="editfield">
                 <div id ="view-content">
                     <h1> Category List </h1>
                     <div class="Add-button">
                        <a href="<?php echo $this->url(array('controller' =>'catalog', 'action'=>'addcategory')); ?>">Add Category</a>
                     </div>     
                     <ul class="category_list" >
                        <?php  foreach ($this -> categories as $category) : ?>
                         <?php if ($category -> parent_id == 0 ): ?>
                         <li><a href="<?php echo $this -> url(array('controller'=>'catalog', 'action'=>'editcategory','id'=>$category -> product_category_id)); ?>" ><?php echo $category -> category_name; ?></a></li>
                            <?php  foreach ($this -> subcategories as $subcategory): ?>
                            <?php if ($subcategory -> parent_id == $category -> product_category_id): ?>
                            <li><a href="<?php echo $this -> url(array('controller'=>'catalog', 'action'=>'editcategory','id'=>$subcategory -> product_category_id)); ?>" >---------  <?php echo $subcategory -> category_name; ?></a></li>
                            <?php endif; ?>
                            <?php endforeach; ?>
                         <?php endif; ?>
                        <?php endforeach; ?>
                     </ul>
             
                 </div>
             </td>
        </tr>
</table>