<table class="product_table" width="100%">
        <tr>
          <td width="20%" class="listfield">  
              <div class="left-bar">
              <ul class="side-menu">
                  <li><a href="<?php echo $this->url(array('controller'=>'catalog', 'action'=>'category')); ?>" >Create Category</a></li>
              </ul>
              </div>
          </td>
             
          <td width="1" bgcolor="black"></td> 
             
          <td width="80%" class="editfield">
                 <div id ="view-content">
              
                 </div>
             </td>
        </tr>
</table>