<a href="<?php echo $this->url(array('controller' =>'cover', 'action'=>'add')); ?>">Add new cover</a>
<table class="product_list">
    <caption>
        Cover
    </caption>
    <tr>
       <td> Name </td>
       <td> Item Code </td>
       <td> Price </td>
       <td> Size </td>
       <td colspan ="2"> Action </td>
    </tr>
    
    <?php foreach ( $this -> all as $product) : ?>
    <tr>
      <td> <?php echo $product-> product_name; ?></td>
      <td> <?php echo $product-> item_code; ?></td>
      <td> <?php echo $product-> price; ?> </td>
      <td><?php echo $product-> size; ?></td>
      <td> <a href="<?php echo $this->url(array("controller"=>"cover","action"=>"edit","id"=>$product->product_id)); ?>">Update</a>
           <a href="<?php echo $this->url(array("controller"=>"cover","action"=>"delete","id"=>$product->product_id)); ?>">Delete</a>
      </td>       
    </tr>
    <?php endforeach; ?>
</table>