<script>
  $(document).ready(function(){
      $(".product-view tr:even").css("color", "white");
      $(".product-view tr:even").css("background-color", "grey");
  });
</script>
<div id="product-content">
	<?php // Zend_Debug::dump($this -> product) ;
                  $product = $this -> product; ?>
    <h1>Surfboard</h1>
    <table class ="product-view">
        <tr><td>Item Code</td><td><?php echo $product['item_code']; ?></td></tr>
        <tr><td>Cover Name</td><td><?php echo $product['product_name']; ?></td></tr>
        <tr><td>Price</td><td><?php echo $product['price']; ?></td></tr>
        <tr><td>Size</td><td><?php echo $product['size']; ?></td></tr>
        <tr><td>Length</td><td><?php echo $product['length']; ?></td></tr>
        <tr><td>Width</td><td><?php echo $product['width']; ?></td></tr>
        <tr><td>Thickness</td><td><?php echo $product['thickness']; ?></td></tr>
        <tr><td>Weight</td><td><?php echo $product['weight']; ?></td></tr>
        <tr><td>Slot</td><td><?php echo $product['slot']; ?></td></tr>
          
    </table>
    <div class="product-image">
        <img src="<?php echo $this->baseUrl().'/images/products/'.$product['images']; ?>" alt="image" width="500px" height="300px"/>
    </div>
</div>